### ISSUE TITLE
Support other Ruby-like syntaxes like RSpec

### ISSUE THREAD

**Issue by yaroslav** [elomarns/auto-encoding-for-ruby#1]
"RSpec" is a diffirent syntax from "Ruby" in ST2, so the plugin does not seem to work with RSpec files at all.

Maybe keep a list of supported syntaxes somewhere?

**Comment by yaroslav** [comment]
@elomarns great plugin, by the way. Just saying :-)

**Comment by elomarns** [comment]
First of all, thanks for your nice words. It's really good to know someone liked this little piece of code.

About the RSpec issue, I'll fix it but I'm not sure about the better approach. A list of supported syntaxes can be a way to go, but it only makes sense if there's more syntax names related to Ruby that doesn't include the word "ruby". If it's just RSpec, I think it's a better simply change the regex which test the current syntax to make sure the current file it's a Ruby file.

Do you know other syntaxes related to Ruby that doesn't include "ruby" on its name?

**Comment by yaroslav** [comment]
Well, I can only see "Ruby on Rails" syntax in my installation that is also possibly Ruby.

Other than that, your plugin can be useful for putting `# encoding` comments in ERB files, but that is a bit of a different functionality.

**Comment by elomarns** [comment]
The plugin already works with "Ruby on Rails" syntax, as it works with any syntax that has the word "Ruby" on its name.

But I'll take a look on the need of including the encoding declaration on ERB files. This was never necessary on my case, but maybe can benefit other developers.

Thanks for your feedback.

**Comment by elomarns** [comment]
RSpec now triggers the insertion of encoding declarations, so I'm closing this issue.
