### ISSUE TITLE
sublime 3 compatibility

### ISSUE THREAD

**Issue by sdepold** [elomarns/auto-encoding-for-ruby#17]
Hi :)

I guess the plugin is not ST3 compatible as i cannot find it with the package manager anymore?

Greetings,
sdepold

**Comment by elomarns** [comment]
Hi!

If you search for it on Package Control inside ST 3 you'll find it, but it won't work. I'm planning to port it to ST 3, but to be honest, it's not on my priority list. It's gonna happen, but I don't know exactly when.

Greetings! :)
