### ISSUE TITLE
Doesn't work with Sublime Text 3?

### ISSUE THREAD

**Issue by vocino** [elomarns/auto-encoding-for-ruby#18]
I can't seem to get this package to work at all in ST3.

**Comment by elomarns** [comment]
Right now it doesn't work on ST 3, but I'll eventually fix it.

**Comment by kjohnston** [comment]
@elomarns, love the plugin, thanks!  I'm making the leap to Sublime Text 3 and would love to be able to continue using it.  Any plans to add support?
