### ISSUE TITLE
UTF-8 declaration style

### ISSUE THREAD

**Issue by gdelfino** [elomarns/auto-encoding-for-ruby#2]
Nice package! Here is a suggestion to make it better:

I use this declaration in the top of my files:

```
# -*- encoding : utf-8 -*-
```

instead of

```
#encoding: utf-8
```

So when I use this package I end up with double declarations. Maybe the style of the declaration could be make configurable?

**Comment by elomarns** [comment]
I'll make the encoding declaration configurable.

**Comment by elomarns** [comment]
Done.

Now you can set your encoding declaration string with the setting "encoding_declaration", which is "#encoding: utf-8" by default. If you change the default, you also need to give a new value to "encoding_declaration_regex", which is a regex used to check if your file already has encoding declaration.
