### ISSUE TITLE
Breaks Haml files

### ISSUE THREAD

**Issue by whitequark** [elomarns/auto-encoding-for-ruby#3]
Thank you for a nice plugin. Unfortunately, it isn't really usable with Rails at this moment.

The syntax for Haml is called "Ruby Haml", and the "# encoding" has a completely different meaning in haml. I'd suggest it to detect some keywords for alternative syntaxes like Haml and RSpec (from #1), and only fall back to plain Ruby if it couldn't find those keywords. Or maybe you should just hardcode a list of syntax names and magic header types to avoid further accidental breakage.

**Comment by elomarns** [comment]
This and #1 will be fixed soon.

Haml won't trigger encoding declaration insertion anymore.

**Comment by whitequark** [comment]
Awesome, thanks.

**Comment by elomarns** [comment]
Done.

Now Haml won't trigger the plugin anymore. In any case, you can add any syntax to the list of supported syntaxes, and customize the encoding declaration string each syntax will use by overriding  "encoding_declaration" and "encoding_declaration_regex" on syntax settings file.
