### ISSUE TITLE
Wrong coding header generated by the plugin

### ISSUE THREAD

**Issue by demiazz** [elomarns/auto-encoding-for-ruby#4]
WRONG: #encoding: utf-8
RIGHT: # coding: utf-8

http://stackoverflow.com/questions/6444826/ruby-utf-8-file-encoding

**Comment by elomarns** [comment]
I have mixed feelings about this. #coding: utf-8 can be more correct, but #encoding: utf-8 is not wrong, it works fine. And I'm not sure if many developers know that #coding: utf-8 works too. I didn't know it. So maybe if I change the default to #coding: utf-8 I'll let a lot of people confused. 

Anyway, you can always change your encoding declaration string: https://github.com/elomarns/auto-encoding-for-ruby#encoding-declaration

**Comment by demiazz** [comment]
You right, I hastened the opening of ticket. Now, I try write experimental analog of your plugin. I try implement some of my ideas for this task. 

Sorry for my bias, and thank you for your plugin. =)

**Comment by elomarns** [comment]
No need for apologize, in the end I owe you for sharing this link. I would die without knowing that the most correct form is `#coding: utf-8`. So thank you. :)

And good luck with your experiment.
