### ISSUE TITLE
Repeated auto adding header when manually deleted

### ISSUE THREAD

**Issue by demiazz** [elomarns/auto-encoding-for-ruby#5]
When I manually remove inserted header, plugin automated adds them again. I think, this is bad behaviour. 

Plugin must add header only once, and not after manual deleting header by user.

**Comment by elomarns** [comment]
The reason why the plugin adds the encoding declaration again is that it will always be sure that the encoding declaration are present when needed, and that it's never present when not needed. So if you delete it, and the plugin adds it again, the declaration is still needed, and it should not be removed as long as the file still has non-ASCII characters.

And personally I prefer this approach than add it just once. The reason why I've created this plugin is to delegate to it the task of adding and removing the encoding declaration. So when I'm using it I don't want to think about encoding declaration, this is the plugin's job.

**Comment by demiazz** [comment]
Ok. But one moment. If file already has encoding header - plugin try adds own header. May be, plugin should check presence of encoding header, before adds right header, or replace existing.

And how plugin work, when in file using hashbang header? (#! /env/ruby for example)

**Comment by elomarns** [comment]
The plugin already checks if the file has an encoding declaration, but it checks using the default encoding declaration (currently #encoding: utf-8). So If you're using an encoding declaration other than the default, the plugin will add the declaration anyway. In this case you have to set your prefered encoding declaration string, as explained here: https://github.com/elomarns/auto-encoding-for-ruby#encoding-declaration. After this, the plugin will recognize your encoding declaration.

About hashbang headers, the plugin currently ignores it and always add the encoding declaration on the first line. I didn't thought on this case before, and I agree that's not the best behaviour. So I'll eventually change it in a way that it adds the encoding declaration on the first blank line.

**Comment by demiazz** [comment]
Ok. =) I start experiment with analog your plugin for looking on this task, and I think about solving problem with hashbang headers. May be I can come up with some useful solution.

**Comment by elomarns** [comment]
Good look. :)

I'll eventually try to solve the hashbang problem as well.
