### ISSUE TITLE
Adding encoding header in SLIM templates

### ISSUE THREAD

**Issue by demiazz** [elomarns/auto-encoding-for-ruby#6]
Plugin adds encoding headers in SLIM templates too. Encoding header don't needed in templates.

**Comment by elomarns** [comment]
Are you using the latest version of the plugin?

Currently, it's activated by default only on Ruby, Ruby on Rails and RSpec syntaxes. 

I believe you're using a previous version, where any syntax with "Ruby" on its name  would activate the plugin.

**Comment by demiazz** [comment]
Ok, I'm try install plugin by adding github repo in Package Installer.

**Comment by elomarns** [comment]
You can also remove it and add it again with Package Control. By the way, I think this is the best way to install it and manage it.

**Comment by demiazz** [comment]
Thank you. I will try do this.

**Comment by elomarns** [comment]
If the problem remains, please let me know.
