### ISSUE TITLE
Check encoding only on load and save

### ISSUE THREAD

**Issue by bquorning** [elomarns/auto-encoding-for-ruby#8]
In my opinion, calling `handle_encoding_declaration_on` should only be called on save, that is, change from `on_modified` to `on_pre_save`. I don't like how my text file changes while I am writing.

Maybe this can be configurable?

**Comment by elomarns** [comment]
I prefer to do this checking on every keystroke, but I agree that's a personal choice, and should be configurable. I will do it on the next few days.

**Comment by Eric-Guo** [comment]
I also prefer checking only on save and [here is the code change pull](https://github.com/elomarns/auto-encoding-for-ruby/pull/12)

**Comment by elomarns** [comment]
It's on master now.

Thanks for the pull request, @Eric-Guo.
