### ISSUE TITLE
optionally do not remove encoding comment

### ISSUE THREAD

**Issue by schnittchen** [elomarns/auto-encoding-for-ruby#9]
It would be nice to have a config option to switch off removal of the encoding comment.

**Comment by elomarns** [comment]
The encoding comment is removed only when it's not necessary anymore. So I think there's no reason why don't remove it, as the plugin will add it again if needed.

**Comment by schnittchen** [comment]
There is no harm done by an unused encoding statement. Also, not removing it would keep version control history clearer of unrelated changes.

**Comment by Eric-Guo** [comment]
Seems you just need [this change](https://github.com/elomarns/auto-encoding-for-ruby/pull/11), hoping elomarns can merge it into master soon.

**Comment by elomarns** [comment]
It's on master now.

Thanks for the pull request, @Eric-Guo.
